from __future__ import print_function
import os, site

def main():
    package = os.path.dirname(os.path.abspath(__file__))

    pathspec = r"""
    # Generated by Stem's installer (install_locally.py)
    # In the lines below, list the paths where Python should look for
    # supplied modules, one directory per line.
    #
    # If a directory does not exist when Python is started, it will be ignored.
    %s
    """ % package

    print("Adding path:", package)

    usp = site.getusersitepackages()
    if not os.path.exists(usp):
        os.makedirs(usp)
    uspfile = os.path.join(usp, 'stem.pth')
    with open(uspfile, 'w') as outfile:
        outfile.write(pathspec)
    print('Wrote to ' + uspfile)
    print("Cord package installed successfully!")

if __name__ == '__main__':
    main()
